# Generated by Django 5.2 on 2025-04-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progress records'},
        ),
        migrations.AddField(
            model_name='progress',
            name='completion_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('user', 'course_id')},
        ),
    ]
