# Generated by Django 5.2 on 2025-04-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_progress_options_progress_completion_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='comleted_modules',
            field=models.JSONField(default=list),
        ),
    ]
