# Generated by Django 5.2 on 2025-04-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_progress_comleted_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='last_accessed',
            field=models.DateField(auto_now=True),
        ),
    ]
