# Generated by Django 5.2 on 2025-04-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='courses/materials/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('video', 'Видео'), ('text', 'Текст'), ('quiz', 'Тест'), ('image', 'Изображение')], max_length=10),
        ),
    ]
