# Generated by Django 5.2 on 2025-05-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_module_options_remove_material_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('video', 'Видео'), ('text', 'Текст'), ('image', 'Изображение')], max_length=10),
        ),
    ]
