# Generated by Django 5.2 on 2025-05-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='test',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
